// Common Indian banks shown first in the employee bank picker.
export const BANK_OPTIONS = [
  'State Bank of India',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Punjab National Bank',
  'Bank of Baroda',
  'Canara Bank',
  'Union Bank of India',
  'Bank of India',
  'Central Bank of India',
  'Indian Bank',
  'Indian Overseas Bank',
  'UCO Bank',
  'Bank of Maharashtra',
  'Punjab and Sind Bank',
  'IDBI Bank',
  'Kotak Mahindra Bank',
  'IndusInd Bank',
  'Yes Bank',
  'Federal Bank',
  'South Indian Bank',
  'RBL Bank',
  'AU Small Finance Bank',
  'Bandhan Bank',
  'IDFC FIRST Bank',
  'City Union Bank',
  'Karnataka Bank',
  'Karur Vysya Bank',
  'DCB Bank',
  'CSB Bank',
  'Tamilnad Mercantile Bank',
  'Jammu and Kashmir Bank',
  'DBS Bank India',
  'HSBC India',
  'Standard Chartered Bank',
  'Deutsche Bank',
] as const;

export const BANK_SEARCH_ALIASES: Record<string, string[]> = {
  'State Bank of India': ['sbi'],
  'Punjab National Bank': ['pnb'],
  'Bank of Baroda': ['bob'],
  'Union Bank of India': ['ubi'],
  'Central Bank of India': ['cbi'],
  'Indian Overseas Bank': ['iob'],
  'IDFC FIRST Bank': ['idfc'],
  'Karur Vysya Bank': ['kvb'],
  'Tamilnad Mercantile Bank': ['tmb'],
  'City Union Bank': ['cub'],
  'Jammu and Kashmir Bank': ['j&k bank', 'jkb'],
};
